Publishing to npm
IDEMSInternational/safeguarding-rapidpro pull request #5
Opened 2023-05-30 20:21 UTC by edmoss345

Small changes made to publish to npm

2023-06-05 10:19 UTC, istride requested changes

2023-06-05 10:19 UTC, istride commented on package.json
>    "license": "ISC",
GPL-3.0-only

2023-06-05 10:19 UTC, istride commented on index.js
I think it's a bit odd to do leave this file empty. This should be the entry point into this library, for example, what do want to happen when someone writes:
```
const x = require('safeguarding-rapidpro');
```

I can appreciate that the code in this repo needs refactoring before we can do anything meaningful in this file (exporting functions), but I hope there is an intention to do so in the future.

2023-06-07 14:03 UTC, edmoss345 commented on index.js
Yes agreed, mainly just put this in as a placeholder so we are pointing to a clear entry point in the 'package.json' file, have added a comment just explaining that this file should be improved in future development. Ideal future state is that the functions we want to expose are referenced and can be called as a library or package

2023-06-07 14:07 UTC, edmoss345 commented on package.json
>    "license": "ISC",
changed

2023-06-29 02:10 UTC, merged